//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MayankEntities : DbContext
    {
        public MayankEntities()
            : base("name=MayankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamsDetail> TeamsDetails { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
    
        public virtual ObjectResult<getAll_Result> getAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAll_Result>("getAll");
        }
    
        public virtual ObjectResult<Nullable<int>> RETURNSOMETHING()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("RETURNSOMETHING");
        }
    }
}
